// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'description': string;
  'error': string;
  'formRow': string;
  'importButton': string;
  'label': string;
  'pathInput': string;
  'result': string;
  'resultTable': string;
  'resultTitle': string;
  'resultValue': string;
}
export const cssExports: CssExports;
export default cssExports;
