// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancelBtn': string;
  'cancelCell': string;
  'empty': string;
  'message': string;
  'slotsBar': string;
  'slotsBreakdown': string;
  'slotsSummary': string;
  'slotsWarning': string;
  'stateLabel': string;
  'status': string;
  'thumbnail': string;
  'thumbnailCell': string;
  'title': string;
  'waitTime': string;
}
export const cssExports: CssExports;
export default cssExports;
