// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'message': string;
  'status': string;
  'thumbnail': string;
  'thumbnailCell': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
