// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardName': string;
  'cards': string;
  'sourceCard': string;
  'statusConfigured': string;
  'statusUnconfigured': string;
}
export const cssExports: CssExports;
export default cssExports;
