// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'channelInfo': string;
  'channelList': string;
  'channelOption': string;
  'channelPlatform': string;
  'channelSelected': string;
  'channelThumb': string;
  'channelTitle': string;
  'noResults': string;
  'noSources': string;
  'platformTab': string;
  'platformTabActive': string;
  'platformTabs': string;
  'searchButton': string;
  'searchInput': string;
  'searchRow': string;
}
export const cssExports: CssExports;
export default cssExports;
