// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'channelBadge': string;
  'channels': string;
  'pathLabel': string;
  'pathRow': string;
  'result': string;
  'resultDescription': string;
  'resultInfo': string;
  'resultName': string;
  'searchButton': string;
  'searchInput': string;
  'searchRow': string;
  'thumbnail': string;
}
export const cssExports: CssExports;
export default cssExports;
