// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addHint': string;
  'channelBadge': string;
  'channels': string;
  'clearButton': string;
  'configForm': string;
  'configLabel': string;
  'configRow': string;
  'configSelect': string;
  'existingHint': string;
  'resultCard': string;
  'resultCardExisting': string;
  'resultDescription': string;
  'resultInfo': string;
  'resultName': string;
  'searchIcon': string;
  'searchInput': string;
  'searchRow': string;
  'selectedCreator': string;
  'selectedName': string;
  'thumbnail': string;
  'thumbnailPlaceholder': string;
}
export const cssExports: CssExports;
export default cssExports;
