// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'detail': string;
  'externalLink': string;
  'filePath': string;
  'loading': string;
  'table': string;
  'thumbnail': string;
}
export const cssExports: CssExports;
export default cssExports;
