// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'channelTitle': string;
  'chevron': string;
  'chevronCollapsed': string;
  'contentThumbnail': string;
  'contentThumbnailImg': string;
  'count': string;
  'emptyNote': string;
  'header': string;
  'platformBadge': string;
  'section': string;
  'statusBadge': string;
  'statusDownloaded': string;
  'statusMissing': string;
  'statusUnmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
