// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'monitor': string;
  'monitorAll': string;
  'monitorBadge': string;
  'monitorFilter': string;
  'monitorNone': string;
  'nextLive': string;
  'progress': string;
  'progressBar': string;
  'progressFill': string;
  'progressText': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
