// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'monitor': string;
  'nextLive': string;
  'progress': string;
  'progressBar': string;
  'progressComplete': string;
  'progressEmpty': string;
  'progressIncomplete': string;
  'thumbnail': string;
  'thumbnailImg': string;
  'thumbnailPlaceholder': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
