// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'cancelBtn': string;
  'channelTitle': string;
  'checkLabel': string;
  'chevron': string;
  'chevronCollapsed': string;
  'confirmBtn': string;
  'contentThumbnail': string;
  'contentThumbnailImg': string;
  'count': string;
  'deleteBtn': string;
  'deleteConfirm': string;
  'deletePrompt': string;
  'downloadCell': string;
  'emptyNote': string;
  'filterInput': string;
  'header': string;
  'headerActions': string;
  'iconBtn': string;
  'iconBtnActive': string;
  'platformBadge': string;
  'saveBtn': string;
  'section': string;
  'settings': string;
  'settingsActions': string;
  'settingsLabel': string;
  'settingsRow': string;
  'statusBadge': string;
  'statusDownloaded': string;
  'statusDownloading': string;
  'statusExpired': string;
  'statusMissing': string;
  'statusModified': string;
  'statusNotAired': string;
  'statusOnAir': string;
  'statusUnmonitored': string;
  'titleLink': string;
  'typeBadge': string;
  'typeLive': string;
  'typeShort': string;
  'typeVideo': string;
}
export const cssExports: CssExports;
export default cssExports;
