// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarCancelBtn': string;
  'avatarEdit': string;
  'avatarEditBtn': string;
  'avatarInput': string;
  'avatarSaveBtn': string;
  'avatarWrap': string;
  'channelBadge': string;
  'channelCard': string;
  'channelList': string;
  'channelRow': string;
  'channelSectionWrap': string;
  'channelTitle': string;
  'channelUrl': string;
  'contentThumbnail': string;
  'contentThumbnailImg': string;
  'header': string;
  'headerDescription': string;
  'headerInfo': string;
  'headerMeta': string;
  'headerThumbnail': string;
  'headerTitle': string;
  'reorderBtn': string;
  'reorderBtns': string;
  'section': string;
  'sectionTitle': string;
  'statusBadge': string;
  'statusDownloaded': string;
  'statusMissing': string;
  'statusMonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
