// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarPlaceholder': string;
  'body': string;
  'configField': string;
  'configForm': string;
  'configLabel': string;
  'configRow': string;
  'configSelect': string;
  'description': string;
  'details': string;
  'fieldHint': string;
}
export const cssExports: CssExports;
export default cssExports;
