// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'info': string;
  'liveBadge': string;
  'meta': string;
  'monitorToggle': string;
  'progressBar': string;
  'progressLabel': string;
  'progressWrap': string;
  'thumbnail': string;
  'thumbnailContainer': string;
  'thumbnailPlaceholder': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
