// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButtons': string;
  'actionsCell': string;
  'body': string;
  'channelOption': string;
  'channelPicker': string;
  'chevron': string;
  'chevronCollapsed': string;
  'count': string;
  'dateCell': string;
  'empty': string;
  'error': string;
  'fileNameCell': string;
  'header': string;
  'reasonCell': string;
  'section': string;
  'sectionLabel': string;
  'sizeCell': string;
}
export const cssExports: CssExports;
export default cssExports;
