// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteBtn': string;
  'deleteCell': string;
  'empty': string;
  'fileName': string;
  'helpText': string;
  'stale': string;
}
export const cssExports: CssExports;
export default cssExports;
