// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'detail': string;
  'empty': string;
  'eventBadge': string;
  'eventDeleted': string;
  'eventDownloaded': string;
  'eventFailed': string;
}
export const cssExports: CssExports;
export default cssExports;
