// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'addBtn': string;
  'empty': string;
  'flagCell': string;
  'header': string;
  'nameCell': string;
  'schemaItem': string;
  'schemaList': string;
  'schemaName': string;
  'table': string;
  'title': string;
  'typeCell': string;
}
export const cssExports: CssExports;
export default cssExports;
