// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCard': string;
  'cardName': string;
  'cardType': string;
  'cards': string;
  'notificationCard': string;
  'providerGrid': string;
  'statusDisabled': string;
  'statusEnabled': string;
}
export const cssExports: CssExports;
export default cssExports;
