// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'empty': string;
  'error': string;
  'folderCell': string;
  'folderControls': string;
  'importActions': string;
  'linkButton': string;
  'pathCell': string;
  'result': string;
  'resultTable': string;
  'resultTitle': string;
  'resultValue': string;
  'rootItem': string;
  'rootItemActive': string;
  'rootItemPath': string;
  'rootItemStatus': string;
  'rootList': string;
  'row': string;
  'rowSelected': string;
  'section': string;
  'sectionTitle': string;
  'selectedCount': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
