// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'error': string;
  'folderCell': string;
  'folderControls': string;
  'footer': string;
  'pathCell': string;
  'result': string;
  'resultTable': string;
  'resultTitle': string;
  'resultValue': string;
  'scanning': string;
  'selectedCount': string;
}
export const cssExports: CssExports;
export default cssExports;
