// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'channelSelect': string;
  'container': string;
  'helpText': string;
  'input': string;
  'inputRow': string;
  'resolvedTitle': string;
  'resultAlert': string;
  'targetPicker': string;
}
export const cssExports: CssExports;
export default cssExports;
