// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'hint': string;
  'input': string;
  'label': string;
  'mixedNote': string;
  'section': string;
  'sectionTitle': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
