// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'centeredCell': string;
  'channelLink': string;
  'checkCell': string;
  'empty': string;
  'platformFilter': string;
  'row': string;
  'rowSelected': string;
  'searchInput': string;
  'selectBar': string;
  'selectBarCount': string;
  'selectBarSpacer': string;
  'sortableHeader': string;
  'table': string;
  'toolbarGroup': string;
  'wordCell': string;
}
export const cssExports: CssExports;
export default cssExports;
